name: Security check - Bandit

on:
  push:
    branches:
      - main
jobs:
  bandit:
    name: "Security check - Bandit"
    runs-on: ubuntu-latest
    steps:
     - name: Git clone the repository
       uses: actions/checkout@v3
     - name: Setup Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.10'
     - run: python test.py
     
     - name: Security check report artifacts
       uses: actions/upload-artifact@v1
       # if: failure()
       with:
         name: Security report
         path: output/security_report.txt
