name: salus
on:
  push:
    branches:
      - poc-sast

jobs:
  salus_scan_job:
    runs-on: ubuntu-latest
    name: Salus Security Scan Example
    steps:
    - uses: actions/checkout@v1
    - name: Salus Scan
      id: salus_scan
      uses: federacy/scan-action@0.1.4
      env:
        BANDIT_VERSION: 1.7.4
      with:
          REPORT_URI: file://output/salus-report.json

        # active_scanners: "\n  - Brakeman"
        # enforced_scanners: "none"
    - name: Security check report artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Security report
        path: output/salus-report.json
